### ISSUE TITLE
Argon2 salt reuse is intended?

### ISSUE THREAD

**Issue by D3vl0per** [f01c33/enc-pad#2]
Why are you reusing the salt in the KDF function?

If you have problems with the persistent storage of salt, you may want to insert salt at the beginning or end of the file as a basic method. 

I know it's not AES, but you might want to check out the https://github.com/FiloSottile/age project.
Here a dedicated header is used to store the keys, similar to LUKS.

**Comment by f01c33** [comment]
Good idea, will do the change

**Comment by f01c33** [comment]
done changes
